#!/bin/sh

##
# HubSpot API contacts download
#
# Syntax:
#
#     hubspot-api-contacts-download
#
# This tool is for [HubSpot](https://hubspot.com) account users.
# This tool connects to the HubSpot API and downloads contacts.
#
# The output is a series of JSON files with file names that
# show the "visitor identification" (vid) offset number and
# the requested record count limit.
#
# Example output file names:
#
#     contacts-vid-offset-0-limit-100.json
#     contacts-vid-offset-3051-limit-100.json
#     contacts-vid-offset-4753-limit-100.json
#
# This tool also combines the files' contacts into one file name:
#
#     contacts.json
#
# Author: joel@joeparkerhenderson.com
##

##
#
# sixarm-unix-shell-functions library
#
##

# out: print output message to stdout
out() { printf %s\\n "$*" ; }

# err: print error message to stderr
err() { >&2 printf %s\\n "$*" ; }

# die: print error message to stderr, then exit with error code 1
die() { >&2 printf %s\\n "$*" ; exit 1 ; }

# cmd: return true iff a command exists
cmd() { command -v "$1" >/dev/null 2>&1 ; }

##
#
# HubSpot API
#
##

# Get HubSpot API URI to download
# Syntax: uri $offset $limit 
uri() {
    out "https://api.hubapi.com/contacts/v1/lists/all/contacts/all?hapikey=$HUBSPOT_API_KEY&vidOffset=$1&count=$2&propertyMode=value_and_history&formSubmissionMode=all&showListMemberships=true"
}

# Get name to save the data file
# Syntax: file_name $offset $limit
file_name() {
    out "contacts-offset-$1-limit-$2.json"   
}

# Does the file indicate that there's more to download?
# Syntax: file_has_more $file_name
file_has_more() {
    jq '."has-more"' "$1"
}

# Get the file's HubSpot vistor identifier offset
# Syntax: file_vid_offset $file_name
file_vid_offset() {
    jq '."vid-offset"' "$1"
}

# Combine all the response contacts files into one big file
# Syntax: file_join
file_join() {
    jq -s 'reduce .[].contacts as $item ([]; . + $item)' contacts-offset-*-limit-*.json > contacts.json
}

# Verify preflight
# Syntax: preflight
preflight() {
    [ -z ${HUBSPOT_API_KEY+x} ] && die "Environment needed: HUBSPOT_API_KEY"
    cmd curl || die "Command needed: curl (HTTP downloader)"
    cmd jq || die "Command needed: jq (JSON processor)"
}

# Main function
# Syntax: main
main() {
    offset=0
    limit=100
    while true; do
        file_name=$(file_name $offset $limit)
        test -e "$file_name" || curl -s $(uri $offset $limit) > "$file_name"
        more=$(file_has_more "$file_name")
        if [ "$more" != "true" ]; then
            break
        fi
        offset=$(file_vid_offset "$file_name")
    done
    file_join
}

preflight
main
exit 0
